language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  - PHPUNIT_VERSION="3.7.*"
  - PHPUNIT_VERSION="3.8.*"
  - PHPUNIT_VERSION="4.0.*"
  - PHPUNIT_VERSION="4.1.*"
  - PHPUNIT_VERSION="4.2.*"
  - PHPUNIT_VERSION="4.3.*"
  - PHPUNIT_VERSION="4.4.*"
  - PHPUNIT_VERSION="4.5.*"
  - PHPUNIT_VERSION="4.6.*"
  - PHPUNIT_VERSION="4.7.*"
  - PHPUNIT_VERSION="4.8.*"
  - PHPUNIT_VERSION="5.0.*"
  - PHPUNIT_VERSION="5.1.*"
  - PHPUNIT_VERSION="5.2.*"
  - PHPUNIT_VERSION="5.3.*"
  - PHPUNIT_VERSION="5.4.*"
  - PHPUNIT_VERSION="5.5.*"
  - PHPUNIT_VERSION="5.6.*"
  - PHPUNIT_VERSION="5.7.*"
  - PHPUNIT_VERSION="6.0.*"
  - PHPUNIT_VERSION="6.1.*"
  - PHPUNIT_VERSION="6.2.*"
  - PHPUNIT_VERSION="6.3.*"
  - PHPUNIT_VERSION="6.4.*"
  - PHPUNIT_VERSION="6.5.*"
  - PHPUNIT_VERSION="7.0.*"
  - PHPUNIT_VERSION="7.1.*"
  - PHPUNIT_VERSION="7.2.*"
  - PHPUNIT_VERSION="dev-master"
  
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - ./.travis.install.sh

script:
  - vendor/bin/phpunit --configuration phpunit-unit.xml.dist
  - vendor/bin/phpunit --configuration phpunit-integration.xml.dist
  - vendor/bin/athletic --path tests/PHPUnit/Tests/Runner/CleverAndSmart/Benchmark --bootstrap tests/PHPUnit/Tests/Runner/CleverAndSmart/Benchmark/bootstrap.php --formatter GroupedFormatter
